name: Adam Page
domain: adam.page
defaults:
  page:
    title: |
      Adam Page — web designer and developer in Portland, Oregon
    meta:
      description: |
        Adam Page is an accessibility-focused user experience designer and
        frontend developer in Portland, Oregon USA.
theme:
  colors:
    background: '#e7eeee'
    icon: '#446060'
